name: Build & serve site
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch gh-pages branch
        run: |
          git fetch origin gh-pages --depth 1
      - name: Prep Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pip deps
        run: |
          python -m pip install --user mkdocs-material mkdocstrings[python] pymdown-extensions
      - name: Build and deploy site
        run: mkdocs gh-deploy
