name: Delete site version for deleted branch
on: delete

concurrency:
  group: gh-pages
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  deploy:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - name: Configure github actions user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install dependencies
        run: uv sync
      - name: Sanitize branch name
        id: sanitize
        run: |
          branch="${{ github.event.ref }}"
          echo "branch=${branch//\//-}" >> "$GITHUB_OUTPUT"
      - name: Delete version for branch
        run: uv run mike delete -p ${{ steps.sanitize.outputs.branch }}
