name: Delete site version for deleted branch
on: delete

permissions:
  contents: write

env:
  NO_MKDOCS_2_WARNING: 1

jobs:
  deploy:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Configure github actions user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync
      - name: Delete version for branch
        run: uv run mike delete -p ${{ github.event.ref }}
