name: Build & serve master
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

concurrency:
  group: gh-pages
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Configure github actions user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - name: Install dependencies
        run: uv sync
      - name: Build and deploy master
        run: uv run mike deploy -p -u master
      - name: Set default
        run: uv run mike set-default -p master
