name: Build & serve master
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

concurrency:
  group: gh-pages
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - name: Configure github actions user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Install uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
      - name: Install dependencies
        run: uv sync
      - name: Build and deploy master
        run: uv run mike deploy -p -u master
      - name: Set default
        run: uv run mike set-default -p master
