name: Build & serve master
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Configure github actions user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync
      - name: Build and deploy master
        run: uv run mike deploy -p -u master
      - name: Set default
        run: uv run mike set-default -p master
